CREATE SCHEMA IF NOT EXISTS focus;

DROP TABLE IF EXISTS focus.cost_usage;

CREATE TABLE focus.cost_usage (
    "AllocatedMethodDetails" jsonb,
    "AllocatedMethodId" text,
    "AllocatedResourceId" text,
    "AllocatedResourceName" text,
    "AllocatedTags" jsonb,
    "AvailabilityZone" text,
    "BilledCost" numeric(20, 6),
    "BillingAccountId" text NOT NULL,
    "BillingAccountName" text,
    "BillingAccountType" text,
    "BillingCurrency" char(3) NOT NULL,
    "BillingPeriodCreated" timestamptz,
    "BillingPeriodEnd" timestamptz NOT NULL,
    "BillingPeriodLastUpdated" timestamptz,
    "BillingPeriodStart" timestamptz NOT NULL,
    "BillingPeriodStatus" text,
    "CapacityReservationId" text,
    "CapacityReservationStatus" text,
    "ChargeCategory" text NOT NULL,
    "ChargeClass" text,
    "ChargeDescription" text,
    "ChargeFrequency" text,
    "ChargePeriodEnd" timestamptz NOT NULL,
    "ChargePeriodStart" timestamptz NOT NULL,
    "CommitmentDiscountCategory" text,
    "CommitmentDiscountId" text,
    "CommitmentDiscountName" text,
    "CommitmentDiscountQuantity" numeric(20, 6),
    "CommitmentDiscountStatus" text,
    "CommitmentDiscountType" text,
    "CommitmentDiscountUnit" text,
    "CommitmentProgramEligibilityDetails" jsonb,
    "ConsumedQuantity" numeric(20, 6),
    "ConsumedUnit" text,
    "ContractApplied" boolean,
    "ContractCommitmentApplicability" text,
    "ContractCommitmentBenefitCategory" text,
    "ContractCommitmentCategory" text,
    "ContractCommitmentCost" numeric(20, 6),
    "ContractCommitmentCreated" timestamptz,
    "ContractCommitmentDescription" text,
    "ContractCommitmentDiscountPercentage" numeric(20, 6),
    "ContractCommitmentDurationType" text,
    "ContractCommitmentFulfillmentInterval" text,
    "ContractCommitmentId" text,
    "ContractCommitmentLastUpdated" timestamptz,
    "ContractCommitmentLifecycleStatus" text,
    "ContractCommitmentModel" text,
    "ContractCommitmentOfferCategory" text,
    "ContractCommitmentPaymentInterval" text,
    "ContractCommitmentPaymentModel" text,
    "ContractCommitmentPaymentUpfrontPercentage" numeric(20, 6),
    "ContractCommitmentPeriodEnd" timestamptz,
    "ContractCommitmentPeriodStart" timestamptz,
    "ContractCommitmentQuantity" numeric(20, 6),
    "ContractCommitmentType" text,
    "ContractCommitmentUnit" text,
    "ContractId" text,
    "ContractPeriodEnd" timestamptz,
    "ContractPeriodStart" timestamptz,
    "ContractedCost" numeric(20, 6),
    "ContractedUnitPrice" numeric(20, 6),
    "EffectiveCost" numeric(20, 6) NOT NULL,
    "HostProviderName" text,
    "InvoiceDetailCreated" timestamptz,
    "InvoiceDetailDescription" text,
    "InvoiceDetailGrain" text,
    "InvoiceDetailId" text,
    "InvoiceDetailLastUpdated" timestamptz,
    "InvoiceId" text,
    "InvoiceIssueDate" date,
    "InvoiceIssueStatus" text,
    "InvoiceIssuerName" text,
    "ListCost" numeric(20, 6),
    "ListUnitPrice" numeric(20, 6),
    "PaymentCurrency" char(3),
    "PaymentCurrencyBilledCost" numeric(20, 6),
    "PaymentCurrencyInvoiceDetailId" text,
    "PaymentDueDate" date,
    "PaymentTerms" text,
    "PricingCategory" text,
    "PricingCurrency" char(3),
    "PricingCurrencyContractCommitmentCost" numeric(20, 6),
    "PricingCurrencyContractedUnitPrice" numeric(20, 6),
    "PricingCurrencyEffectiveCost" numeric(20, 6),
    "PricingCurrencyListUnitPrice" numeric(20, 6),
    "PricingQuantity" numeric(20, 6),
    "PricingUnit" text,
    "PurchaseOrderNumber" text,
    "ReferenceInvoiceId" text,
    "RegionId" text,
    "RegionName" text,
    "ResourceId" text,
    "ResourceName" text,
    "ResourceType" text,
    "ServiceCategory" text,
    "ServiceName" text NOT NULL,
    "ServiceProviderName" text NOT NULL,
    "ServiceSubcategory" text,
    "SkuId" text,
    "SkuMeter" text,
    "SkuPriceDetails" jsonb,
    "SkuPriceId" text,
    "SubAccountId" text,
    "SubAccountName" text,
    "SubAccountType" text,
    "Tags" jsonb NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE focus.cost_usage IS
    'FOCUS 1.4 Cost and Usage demo table with all 107 standard columns.';

CREATE INDEX IF NOT EXISTS idx_cost_usage_charge_period
    ON focus.cost_usage ("ChargePeriodStart", "ChargePeriodEnd");

CREATE INDEX IF NOT EXISTS idx_cost_usage_provider_service
    ON focus.cost_usage ("ServiceProviderName", "ServiceName");

CREATE INDEX IF NOT EXISTS idx_cost_usage_tags_gin
    ON focus.cost_usage USING gin ("Tags");
